version: '3'
services:
  fuel-calc:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    command:
      - mysql -u root -ppassword < /home/mbfuelcalculator/FuelCostCalculator/dbinit
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./redis-volume:/data
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"
  db:
    image: 'mysql'
    container_name: db